blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/scify/laravel-cookie-guard/discussions/new?category=questions
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/scify/laravel-cookie-guard/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/scify/laravel-cookie-guard/security/advisories
    about: Learn how to notify us for sensitive bugs
  - name: Report a bug
    url: https://github.com/scify/laravel-cookie-guard/issues/new?template=bug_report.md
    about: Report a reproducible bug
