name: "Update Changelog"

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          create_branch: true
          branch: update-changelog
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Updated CHANGELOG.md
          title: Updated CHANGELOG.md
          body: Updated CHANGELOG.md
          base: main
          labels: automated-pr, update-changelog
          branch: update-changelog
          delete-branch: true
